### ISSUE TITLE
Web API tests expected instead of class tests in ChatServiceTest

### ISSUE THREAD

**Issue by gmamaladze** [freeuni-sdp/xo-chat#11]
თქვენი ტესტები `ChatServiceTest` ატესტირებს კლასის ფუნქციონალობას, რაც თავისთავად ურიგო არ არის.
საჭირო სხვა სახის ტესტი რომელიც დაატესტირებას API-ს ანუ რომელ რექვესტზე რა რესპონსი მოდის რა მონაცემით და რა სტატუს კოდით. მაგალითისათვის იხილეთ: [TestTaskService](https://github.com/freeuni-sdp/todo-core/blob/master/test/TestTaskService.java)

**Comment by BeqaKhaburdzania** [comment]
d8b2eb57c64e698b2ad2978beef6296fefb58d18
