### ISSUE TITLE
user name

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-chat#13]
**List all messages**: აოჯბებს, ტოკენის ნაცვლად დააბრუნოს მომხმარებლის სახელი, ვინც ეს შეტყობინება დაწერა. მომხმარებელს უნდა გმაოუჩნდეს შეტყობინების ავტორის სახელი.

**Send a new message**: უკეთესი იქნება თუ ტოკენს გავიტანთ json-დან url-ში `/?toke=token`

**Comment by kurid** [comment]
1-ს გადავაკეთებ.

და ახალი შეტყობინების გაგზავნისას რატომ ჯობია url-ში იყოს ტეოკენი ვერ ვხვდები.

**Comment by gkiko** [comment]
token არ გვჭირდება მონაცემის ერთიანობისთვის. უბრალოდ მომხმარებლის ამოცნობისთვის ვიყენებთ. მომავალში შეგვიძლია token გადავაგდოთ და სტანდარტულ აუთენტიფიკაციის მექანიზმებზე გადავიდეთ, თანაც არ შეგვეცლება გადასაცემი ობიექტი.

სხვა სერვისებსაც url-ში აქვთ token. :grimacing:

**Comment by kurid** [comment]
კარგი, ეგეც გასაგებია. 

კიდევ ერთი კითხვა, თუ შეტყობინებების სიის დაბრუნებისას სახელი უნდა დავაბრუნო ტოკენის ნაცვლად,
მაშინ შეტყობინების გამოგზავნისასაც უნდა სახელი დამატება არა?
აბა ისე საიდან მეცოდინება სახელები...

**Comment by gkiko** [comment]
გამოვა მასე. უფრო უსაფრთხო იქნებოდა
1. token მოგდიოდეს
2. xo-login-დან მოგქონდეს ამ token-ის შესაბამისი სახელი
3. ინახავდე ტექსტს სახელის მიხედვით

მაგრამ ჩვენ უმაგისოდაც გავალთ ფონს

**Comment by kurid** [comment]
კი ეგეც ვიფიქრე.
მაგრამ თუ token-ის მიხედვით სახელის გაგება სწორია,
xo-login-ს token-ის შესაბამისი სახელი xo-chat-მა უნდა ჰკითხოს თუ იმ სერვისმა, რომელიც ვიზუალურ მხარეზეა პასუხისმგებელი?

**Comment by gkiko** [comment]
xo-chat-მა

**Comment by kurid** [comment]
fake იმპლენტაციისთვის გავითვალისწინე ეს შენიშვნები.

ამ ცვლილებების გამო მომიწია, message კლასი 2 ლოგიკურ ერთეულად გამეყო, ერთი SendMessageEntity სადაც მხოლოდ ტექსტი და ოთახის ნომერია. (რადგან  post-ის შემთხვევაში token url-ში გადაეცემა query პარამეტრად) 
და მეორე MessageEntity(roomId, text, senderUserName) -> რომლის ობიექტების სიაც უნდა დავაბრუნოთ get request-ის  შემთხვევაში.

ტესტებსაც შესაბამისად შევცვლით და რეალურ იმპლენტაციასაც ამის მიხედვით გავაკეთებთ.
